trigger:
- master

jobs:
- job: MacTests
  pool:
    vmImage: 'macOS 10.14'
  variables:
    DEVELOPER_DIR: /Applications/Xcode_10.2.app
  steps:
    - script: make test
      displayName: test fixtures