version: 2.1
jobs:
  macOS_swift_5.0:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: 
          name: Test
          command: scripts/test.sh
workflows:
  version: 2.1
  workflow:
    jobs:
      - macOS_swift_5.0